version = 0.1

[default.deploy.parameters]
stack_name = "proyecto-fastapi-stack"
resolve_s3 = true
s3_prefix = "proyecto-fastapi-stack"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
